version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - k-nasa
  ignore:
  - dependency-name: rand
    versions:
    - 0.8.3
  - dependency-name: dirs
    versions:
    - 3.0.1
  - dependency-name: serde
    versions:
    - 1.0.123
    - 1.0.124
    - 1.0.125
  - dependency-name: serde_json
    versions:
    - 1.0.62
