[package]
authors = ["nasa <htilcs1115@gmail.com>"]
edition = "2018"
name = "ai-chan"
version = "0.1.0"
[dependencies]
dirs = "*"
env_logger = "0.6.0"
failure = "*"
log = "*"
rocket = "*"
rocket_contrib = "*"
serde = "*"
serde_derive = "*"
serde_json = "1.0"
toml = "*"
